### ISSUE TITLE
still no idea how to upload images

### ISSUE THREAD

**Issue by renerocksai** [renerocksai/sublime_zk#14]
![sublime_zk4](https://user-images.githubusercontent.com/30892199/32399395-d4dffaf6-c0f5-11e7-8e1c-5a53fefb98a8.png)
![sublime_zk5](https://user-images.githubusercontent.com/30892199/32399400-da7cdcae-c0f5-11e7-88cf-c0b151c153b2.png)

**Comment by toolboxen** [comment]
looks like you figured it out! just upload into this comment area, and then you can grab the `githubusercontent.com` URL with no need to post the actual comment. The URL remains live even if not posted to an issue.

**Comment by renerocksai** [comment]
<img width="1130" alt="oldschool_links" src="https://user-images.githubusercontent.com/30892199/32704052-906b7024-c7ff-11e7-9cb9-57f030408b59.png">

**Comment by renerocksai** [comment]
<img width="1293" alt="adv_tag_search" src="https://user-images.githubusercontent.com/30892199/32980898-2224ec2a-cc6f-11e7-8e8b-a146145af853.png">

**Comment by renerocksai** [comment]
![inline_imgs](https://user-images.githubusercontent.com/30892199/33154565-7df466ac-cfe9-11e7-8920-b204fa4dcb02.gif)

**Comment by renerocksai** [comment]
![link_styles](https://user-images.githubusercontent.com/30892199/33496765-cc8e0c12-d6cb-11e7-8805-b6895c2f1929.png)

**Comment by renerocksai** [comment]
![link_styles](https://user-images.githubusercontent.com/30892199/33497107-fdaf0c50-d6cc-11e7-81d3-27af3ba9e740.png)

**Comment by renerocksai** [comment]
<img width="1316" alt="panes" src="https://user-images.githubusercontent.com/30892199/33515865-e400ca54-d768-11e7-8fba-c641871c0cc0.png">
