### ISSUE TITLE
target multimarkdown with syntax

### ISSUE THREAD

**Issue by toolboxen** [renerocksai/sublime_zk#15]
just putting this here, depending on how #5 turns out it might not be necessary.

Sublime ships with 2 markdown options: Markdown and MultiMarkdown. MultiMarkdown highlighting in Sublime adds a few extra niceties to the Markdown highlighting. (specifically multimarkdown Metadata highlighting) -- I suggest re-targeting MultiMarkdown instead of Markdown to include those niceties in Markdown Zettelkasten.

So Markdown Zettelkasten will extend the default MultiMarkdown, which extends the default Markdown. If Sublime ever updates/improves their Markdown & MultiMarkdown syntaxes, your syntax will inherit both those improvements!

**Comment by toolboxen** [comment]
Suggest pull request in #16

**Comment by renerocksai** [comment]
<img width="930" alt="sublime_zk6" src="https://user-images.githubusercontent.com/30892199/32403197-25d9ccd2-c134-11e7-93c6-62257f35e518.png">

![sublime_zk6a](https://user-images.githubusercontent.com/30892199/32403198-25f55650-c134-11e7-8f62-58fdbfb13c2b.png)

![sublime_zk6b](https://user-images.githubusercontent.com/30892199/32403199-260fb374-c134-11e7-99ad-59e22852a095.png)
