### ISSUE TITLE
Additional feature (original Zettel) for notes template

### ISSUE THREAD

**Issue by wangeleile** [renerocksai/sublime_zk#22]
Would be great to have a variable, which give the original Zettel, where I start to generate a new Zettel. 

You are working on Zettel A, then you SHIFT+ENTER a new Zettel. sublime_zk knows the last Zettel and 
replace the placeholder e.g.  {origin} with the UID [[201711142248]]

 "new_note_template": "---\nuid: {id}\ntags: \n# Verknüpfungen\n - {origin}---\n",

**Comment by renerocksai** [comment]
Done! :)

I used this string (note the extra [[ and the extra \n behind the ]]):

"new_note_template": "---\nuid: {id}\ntags: \n# Verknüpfungen\n - [[{origin}]]\n---\n",

I left the [[ ]] out so people can put in what they want: [] [[]] § ...

:)

**Comment by renerocksai** [comment]
btw it even works with [[implicit note creation]] that is kind of cool.

when playing with it pls bear in mind to create only 1 zettel per minute :)
