### ISSUE TITLE
Using auto-completion to insert note-links includes Link and title

### ISSUE THREAD

**Issue by wangeleile** [renerocksai/sublime_zk#23]
When I generate a buffer file, I have a list of links where I also want see what link it is. 

- [[201711142247]] Zettelkasten Start
- [[201711142050]] Zettelkasten
- [[201711142129]] Sublime Text Editor

Currently I type the title manually. 

Suggestion:
If I select a link (with STRG+Space) and press then ALT+ENTER, it could add the link plus Title like above

**Comment by renerocksai** [comment]
ALT+ENTER is a bad choice for this reason: I am trying it on Linux, where auto-completion is triggered by [ALT]+[/]. Pressing [ALT] while completions are shown, makes the completions go away. 

Anyway, why a special key combination. People tend to either like the one or the other, so I am suggesting a setting `"insert_links_with_titles" : false` -- set it to true and links will **always** be inserted with titles. Would that be an OK compromise?

**Comment by renerocksai** [comment]
To follow-up: auto-completions work this way: upon triggering auto-completion, the plugin has to come up with completions to show and what to insert if they are selected. So at selection time the plugin is not involved anymore and cannot distinguish whether [ALT] was pressed or not.

So I'll go for the setting instead.

**Comment by renerocksai** [comment]
This is implemented now; activate it with

```
"insert_links_with_titles": true,
```
:smile: 
going to update the readme soon.

**Comment by wangeleile** [comment]
Man, you are really fast. Thanks a lot

**Comment by renerocksai** [comment]
You are very welcome! :smile:

**Comment by renerocksai** [comment]
btw if you're registered in the forum of zettelkasten.de and willing to share your identity there, then i can refer to you over there with @wangeleile or something instead of "wangeleile from github" :smile: just an offer
