### ISSUE TITLE
insert_links_with_titles Function also for Origin template field

### ISSUE THREAD

**Issue by wangeleile** [renerocksai/sublime_zk#24]
Regarding the origin field in new templates, I would suggest the same function like implemented with "insert_links_with_titles": true,

Which means, if true also the origin will show the title, if not no title

**Comment by wangeleile** [comment]
Absolutely !! It works perfect and again, this addon fits more and more in my workflow.

**Comment by renerocksai** [comment]
Awesome! So I'm gonna close this one 👍
