### ISSUE TITLE
STRG + Space results in "No available completion "

### ISSUE THREAD

**Issue by wangeleile** [renerocksai/sublime_zk#27]
First of all, wow Rene you are fast. 

I updated the function, but ....

I get some weird reaction when I press STRG + Space, 
Nothing happes, but this message appear. 
![image](https://user-images.githubusercontent.com/183266/33121957-568039c0-cf76-11e7-9f69-81709add202d.png)

When I used behind a written letter, e.g a
this happens

![image](https://user-images.githubusercontent.com/183266/33122113-8bbfbade-cf76-11e7-9713-8e0b483a2c9d.png)

Maybe I have something wrong configured.

**Comment by renerocksai** [comment]
sorry to read that. interesting. when you bring up the sublimetext console with  ctrl+` and try the completion, do you see any error messages?

**Comment by renerocksai** [comment]
I have just pushed a fix for auto-completion if no citekeys are found. if you update, this might just fix your problem.

**Comment by wangeleile** [comment]
Perfect!!! Problem solved. 
1. Path was wrong. I am to blind to see the correct spelling of my username
2. With your fix and the hint, to open the Console I could figure out what the problem was. 

Issue solved

**Comment by renerocksai** [comment]
:+1:
