### ISSUE TITLE
need more than 1 value to unpack

### ISSUE THREAD

**Issue by wangeleile** [renerocksai/sublime_zk#28]
Hi, 

I try to start Auto bib but i get the following error: 

> Traceback (most recent call last):
>   File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 818, in run_
>     return self.run(edit)
>   File "C:\Users\WILMING\AppData\Roaming\Sublime Text 3\Packages\sublime_zk\sublime_zk.py", line 1159, in run
>     ck2bib = Autobib.create_bibliography(text, bibfile, pandoc='pandoc')
>   File "C:\Users\WILMING\AppData\Roaming\Sublime Text 3\Packages\sublime_zk\sublime_zk.py", line 85, in create_bibliography
>     citation, bib = Autobib.parse_pandoc_out(pandoc_out)
>   File "C:\Users\WILMING\AppData\Roaming\Sublime Text 3\Packages\sublime_zk\sublime_zk.py", line 94, in parse_pandoc_out
>     citation, bib, _ = pandoc_out.split('\n\n')
> ValueError: need more than 1 value to unpack

Any idea?

**Comment by renerocksai** [comment]
yes. there seems to be a pandoc issue. I have the same here on Linux. Maybe my macOS pandoc is special, I will work it out. sorry for the inconvenience

**Comment by renerocksai** [comment]
OK, I figured it out. I didn't have `pandoc-citeproc` installed. Once I installed it, the plugin works fine.
If you manage to install it and still have issues, then I just committed some pandoc logging that should let us pin-point the issue.
I just checked: the latest pandoc release for windows https://github.com/jgm/pandoc/releases/tag/2.0.3 does contain pandoc-citeproc.

To find out if this is the issue without  (re-) installing pandoc, you can update this plugin and paste the console output here (it should tell us the pandoc error message due to the new logging).

**Comment by wangeleile** [comment]
Hi, I use the newest pandoc version, but this happens  now ....
![image](https://user-images.githubusercontent.com/183266/33148007-67df3cc6-cfca-11e7-84ae-72b887dde3af.png)

**Comment by wangeleile** [comment]
Console show the full citation, but in the md file it is empty

**Comment by renerocksai** [comment]
😄 OMG! It's 2018 and we still have line termination issues. I see it now: You're working on Windows, which encodes line endings with `\r\n` whereas macOS and Linux use `\n`. This can be fixed and will so, soon. Usually python would shield us from this line termination business... 
I'll fix it but can't test it at the moment - no windows access.

**Comment by wangeleile** [comment]
I can test it ;-), Sorry for using windows

**Comment by renerocksai** [comment]
😄 windows is *fine*! not as bad anymore as it used to be. i'll soon be forced to use it at work, should make testing easier 😄 .

OK, the (I hope) fix is in.

**Comment by renerocksai** [comment]
> windows is fine
never tell anyone I said this 😝

**Comment by wangeleile** [comment]
Windows, who is Windows. 

Fix works perfect. Will close it.

**Comment by renerocksai** [comment]
> Windows, who is Windows.

Don't know... Anybody mentioned Windows? I no see no Windows here... yet... 😉 

Cool that it works now 👍
