### ISSUE TITLE
Highlight Todo, todo, ...

### ISSUE THREAD

**Issue by wangeleile** [renerocksai/sublime_zk#29]
Just a minor request, I use the package todo.review, which is great to find all todo comments. 

For the zettelkasten, I use the Theme from sublime_zk. Could you enhance with highlighting for the word todo: some description for the todo
Todo: some description for the todo

Would make it easy to find open issues.

**Comment by renerocksai** [comment]
Sounds reasonable. Done! I find, it looks awesome, especially in comments!

**Comment by wangeleile** [comment]
Perfect thanks
