### ISSUE TITLE
consider completions API instead of show_overlay

### ISSUE THREAD

**Issue by toolboxen** [renerocksai/sublime_zk#3]
Sublime offers a Completions API which you can populate with your own content to insert into the current view: http://docs.sublimetext.info/en/latest/extensibility/completions.html This list can be triggered manually using a keybind OR it can be triggered with a specific character.

For zettelkasten it would make sense to trigger the completions list with `[[` or `[` and immediately show a list of all notes directly underneath the cursor allowing the user to continue typing to narrow the search using fuzzy matching. This enables the user to not break the flow of typing unlike the current implementation which triggers a modal overlay directly over the text.

**Comment by renerocksai** [comment]
This is an *awesome* idea. I will definitely look into this! I am rather new to SublimeText plugin stuff so thank you for pointing this out. That would be wayyyy cool! :+1:

**Comment by renerocksai** [comment]
I played with this. SublimeText has a big flaw: auto-completion for `[` is not triggered, when `"auto_match_enabled": true`. I would need to find a way to place this setting into a place where it would only affect markdown files and then re-model its behaviour for quotation marks, braces of all sorts, except for square brackets.
I'll not give up now though. Maybe there is a way. Well, there is: if we can use the syntax file -> associated with the "Markdown Zettelkasten" syntax it would work. 

If I remove the footnote stuff would that be an option for you?

**Comment by renerocksai** [comment]
Alternatively Project specific settings would work. So this plugin could create project files .... But that looks ugly to me.

**Comment by renerocksai** [comment]
OK, after playing around with it for a while, I came to the following conclusion:

* it is better and less messing with the rest of the settings one might have to just use the default shortcut for completions, like ctrl+space on OS X and Windows.
* For the [[ feature I keep the `show_overlay` method. 

So we get both now: super-quick link insertion via ctrl+space and for old muscle memory, there is the overlay :).

Will merge the branch soon.

**Comment by renerocksai** [comment]
One more thing which I also mention in the README is that once you exhaust the list of suggestions in auto-complete, the suggestions will disappear. This makes it less handy for searching via trial-and-error. Another reason for leaving the overlay in there as well.

**Comment by renerocksai** [comment]
merged in

**Comment by toolboxen** [comment]
> I played with this. SublimeText has a big flaw: auto-completion for [ is not triggered, when "auto_match_enabled": true.

That's odd. I was testing https://github.com/BoundInCode/AutoFileName the other day, and I set an autocompletion trigger of `[` with `"auto_match_enabled": true` and everything worked absolutely fine for me. Sublime auto-completed the file names without a problem. Pressing `[` would trigger the completions nicely.

> If I remove the footnote stuff would that be an option for you?

I'm not specifically against syntaxes, I elaborated more in #5

**Comment by renerocksai** [comment]
Well, I tried it on my mac with build 3143 and neither `[` nor `(` worked. The closing ones worked, though. That's what lead me to trying to disable `auto_match`.
I have just pushed a branch `feature_syntax_highlighting` addressing #5 so will continue commenting there.
