### ISSUE TITLE
_ instead of SPACE in file name

### ISSUE THREAD

**Issue by wangeleile** [renerocksai/sublime_zk#30]
I am converting single zettel with pandoc to html files. 

201711142050 Zettelkasten.md

Pandoc is not happy with the space between ID and Title

Could it be possible to have a option in settings to select which character should be the delimiter.

**Comment by renerocksai** [comment]
this is certainly doable, 

however the plugin itself uses pandoc for the autobib feature without issues.
i also use pandoc from within sublimetext and it works with my notes all the time, creates html, pdf, etc.

maybe, if you use a script, put " " around the variable for the filename? can you tell me your workflow that involves pandoc, maybe I can help getting this right from that end?

**Comment by renerocksai** [comment]
btw do you use the pandoc sublime package? that should do the trick for you because it works even with spaces in filenames....

**Comment by wangeleile** [comment]
I have just a bat file. Never used it before, so I will look into it and see how it works. Will come back later to this.

**Comment by renerocksai** [comment]
OK, try the quotation marks. Maybe there is a `%1` (or something `%`) -- that would need to become `"%1"`.
