### ISSUE TITLE
set inline image preview size per picture

### ISSUE THREAD

**Issue by 517qf** [renerocksai/sublime_zk#31]
Thank a lot for your work. I don't know much about the sublime eco system but your inline image preview feature seems pretty unique. This alone makes your package great (though I found your package because I was looking for wiki/zettelkasten. Your functions for jumping between notes are also unique for SLT).

I have a small problem with the image preview: Some of my images should be really wide in my buffer, others should be quite narrow. I regularly insert images of diagrams: Some are very detailed and contain lots of information so they need to be shown wide. Some contain very little information and need to be shown narrow: Otherwise I would see big ugly circles and arrows.

The setting img_maxwidth is too general for this problem. As far as I see the only workaround at the moment is too adjust the images permanently in an external editor. 

It would be great if I could override this setting on a per picture basis, i.e. by adding a line with the desired width above the picture. Maybe a line like `<--img_width 700-->`?) I got the idea from emacs-orgmode (which I also evaluated while searching for a plain-text-wiki). In orgmode you would write this:

    #+attr_org: :width 700
    [[file:img/mypicture.jpg][my description]

orgmode seems great but I don't want to spend hundreds of hours learning emacs (and I want to use the more popular markdown). When toggling inline image preview for each image the preceding line is evaluted and the display width is set accordingly.

I think that this might be of general interest because "a picture is worth a thousand words". Thanks for reading my suggestion and again thanks for this great package.

**Comment by renerocksai** [comment]
Hi, 
thx for this great suggestion!
I was suspecting sooner or later a global img width setting wouldn't cut it anymore.
I like your suggestion of an inline comment preceding the image link. Will play around with it but it'll take a day or two because I am overly busy with work.
Will keep you posted!

**Comment by 517qf** [comment]
Thanks for your quick reply and positive reception.

The width setting should be understood outside of sublime-zk: This prevents vendor lock-in and makes the zettelkasten (which hopefully I will use for years) portable and allows to use your zettel without modification for writing a paper. 

The default markdown processor seems to be pandoc. You can pass additional options to pandoc for image width. The syntax is `![](file.jpg){ width=300px }`, see http://pandoc.org/MANUAL.html#images . Contrary to my initial suggestion this style should be adopted. I think that pandoc's solution is also visually better because it alters the layout of a document less.

**Comment by renerocksai** [comment]
Thx for your suggestion, I like the pandoc style (I also like pandoc itself 😄 ).
I am on a train and have a flaky internet connection, so I gotta be quick. It is implenented. Pls check it out and be careful - sublimetext is a bit strange. It won't accept width only, so maybe better use % values. As from the README:

#### Per image preview size
You can define a specific preview size per image by adding image attributes inside a pair of curly braces as shown below:

```markdown
![xxx](img/zettelkasten-book-de.jpg){width=100% height=100%}
![xxx](img/zettelkasten-book-de.jpg){width=200px height=200px}

```

**Note:**

* SublimeText requires you to specify both width and height when you specify your own attributes.
* SublimeText seems to have its own interpretation of how big a pixel is
* If you don't want to manually convert width and height to scaled values, then just use percentages. Start with 100% for each and take it from there.

**Comment by renerocksai** [comment]
Merry Xmas 🎅

**Comment by 517qf** [comment]
Thanks again for your great help. Only today I had time to check out your work. The addon works and now ST is a much better wiki.

**Comment by renerocksai** [comment]
You're welcome! And thanks for bringing this up. Your improvement is now benefiting all ST/sublime_zk users!
