### ISSUE TITLE
Marked word in text + Pressing [Shift][Enter] generate directly a new zettel

### ISSUE THREAD

**Issue by wangeleile** [renerocksai/sublime_zk#34]
To create a new Zettel the shortcut is [Shift][Enter]. When I mark a text and press the shortcut, it would be great that the selected text would be used as title and automatically a new zettel will be created. 
And also the selected word will be embraced with [[]]

**Comment by renerocksai** [comment]
Sorry for the late reply. I'll have more time in the coming weeks. This should be easy enough to do.

**Comment by renerocksai** [comment]
Done: Works the following way: You mark text and press [shift][enter]. The new Zettel field pops up pre-filled with the selected text. So you can just press enter: [shift][enter],[enter] is really quick. The link with the text will be inserted according to the settings.

**Comment by renerocksai** [comment]
![new-note-from-sel](https://user-images.githubusercontent.com/30892199/35771204-d784333c-0928-11e8-85e6-6378d787395d.gif)

**Comment by wangeleile** [comment]
First of all, this solution is perfect, but ...

"insert_links_with_titles": false don't influence that the link is with title or not. 

I would expect to have a link in this style: [[201801281319]] Raspberry Pi
But the result is: [[201801281319 Raspberry Pi]], however true or false .

**Comment by renerocksai** [comment]
Hmm. Thanks for pointing this out.

So to remain consistent, the "new" behaviour is, according to the existing insert_links_with_titles behaviour:

[[201801281319]]
or
[[201801281319]] Raspberry Pi

I have just pushed the fix.

**Comment by renerocksai** [comment]
![new-note-from-sel](https://user-images.githubusercontent.com/30892199/35781566-18734f7c-09ec-11e8-8bd6-c2ee3ed240c1.gif)

**Comment by wangeleile** [comment]
Works like a charm
