### ISSUE TITLE
Support LaTeXTools-like completion of citations

### ISSUE THREAD

**Issue by merlinthered** [renerocksai/sublime_zk#35]
Hi and thanks for this awesome plugin. I am starting to experiment with it and noticed that the autocompletion for BibTex keys only displays the keys themselves. I am rather spoiled by [LaTeXTools'](https://packagecontrol.io/packages/LaTeXTools) way of completing citations. It opens a new command palette at the top populated with the titles and authors of all the bibtex entries, which can be searched just like the regular command palette. Maybe this kind of functionality might also be implemented in sublime_zk. Maybe the code can even be copied from LaTeXTools?

**Comment by renerocksai** [comment]
Hi, I was not aware of LaTeXTools. That's an awesome suggestion! 👍 I will definitely look into it. I included the citekeys to autocompletion, which is different from the fuzzy search command palette style list you get when pressing `[[`. In a way it would be consistent to add bibtex entries to that `[[` list, too. I once thought, including the titles would create a big mess and making it harder to quickly find note titles. So I'm not sure whether to put the bibtex entries into the `[[` list or whether to make a separate list just for citations, which would require a different shortcut key combination. Will play with it and see how it goes...

**Comment by merlinthered** [comment]
If you ever want to write LaTeX with Sublime Text, I cannot recommend LaTeXTools enough. It's one of the most popular Sublime Text plugins for a good reason.

Including titles of citations in the normal autocomplete list is definitely a bad idea. Since citations and links to other zettelkasten documents are conceptually different things, I think it's not necessarily bad to have separate autocomplete lists for them. In fact, I would find it intuitive if the zettelkasten link completion was triggered when pressing `[[`, while citation completion is triggered when pressing `[@`. Not sure how this would interact with multimarkdown-style citations though, which are started in a different way. 

LaTeXTools uses the command palette for all completions and never uses the normal autocomplete list. I never found this particularly disrupting.

**Comment by renerocksai** [comment]
Thanks for your valuable input. I have added a new command to the command palette "ZK: Insert Citation". Uh, just realized: I forgot the key binding to '[@' and '[#'. Will do so in a couple of minutes.

Check it out 😄

**Comment by renerocksai** [comment]
![insert-citation](https://user-images.githubusercontent.com/30892199/35771311-e8da9b06-092a-11e8-847b-aa1649da499d.gif)

**Comment by merlinthered** [comment]
Hey, tanks for reacting so quickly. This looks awesome.

Unfortunately, after the update, I don't get any cite completions at all. After pressing `[@`, the `@` doesn't show up (as it should), and the log says `Using global /.../bibliography.bib`. However, no command palette shows up. When I press the next key, the `@` appears, but nothing else happens.

**Comment by renerocksai** [comment]
Hi, this is weird. 
The only reason for no palette showing up would be if nothing could be found in the bibfile. And in that case it would behave like this: After pressing `[@` the `@` doesn't show up. No command pallette shows up. When pressing the next key, its letter should show up, not the `@`. At least that what happens on my Mac when I empty the bibfile.

Is `Using global ....bib` the only thing that shows up in the console? Or is there a lengthy exception "dump" following it?

Can you try to use the command "ZK: Insert Citation" to check it's not related to the keyboard shortcut. I doubt it is but one never knows.

Failing that, can you send me a snippet of your bibfile? I wonder why it seems to be unparsable. Another user (achamess) reported having a huge bibfile (ca 7500 entries) not causing problems.

Also interesting: do citekeys show up with autocompletion (`ctrl+space` on Win/Mac, `alt+/` on Linux)? If they don't show up there as well, there's definitely something with your bibfile that the plugin doesn't expect.

**Comment by merlinthered** [comment]
The problem was due to some bibtex entries in my .bib file not having a key. I auto-generated keys for them and the command palette worked as expected, but only the entries with the newly generated keys showed up. Then I did a cleanup of the bibtex formatting using JabRef. Now all the entries seem to show up.

It looks like your bib parser needs to become a little more robust. This entry worked for me:
```tex
@InProceedings{Garland1997,
  author    = {M.G. Garland and P.S. Heckbert},
  title     = {Surface Simplification Using Quadric Error Metrics},
  booktitle = {Proc. Siggraph '97},
  year      = {1997},
  pages     = {209--216},
  owner     = {toster},
  timestamp = {2014.12.08},
}
```

While this one did not:

```latex
@Article{Gardner1985,
  Title                    = {Visual Simulation of Clouds},
  Author                   = {Geoffrey Y. Gardner},
  Journal                  = {SIGGRAPH Comput. Graph.},
  Year                     = {1985},
  Number                   = {3},
  Pages                    = {297--304},
  Volume                   = {19},

  Address                  = {New York, NY, USA},
  Doi                      = {10.1145/325165.325248},
  ISSN                     = {0097-8930},
  Owner                    = {toster},
  Publisher                = {ACM},
  Timestamp                = {2014.12.08}
}
```

**Comment by renerocksai** [comment]
Thanks for your feedback and the examples. They help. You're right, the bib parser is not super sophisticated at the moment.

I can confirm that it is case sensitive, when looking for author, title, year -- which causes your second example to be skipped. Well, theoretically, the citekey gets found, but no details to it.

This I can fix easily. 

BTW: Since the lookup is for inserting markdown references via citekey like [@citekey] or [][#citekey], there would be no point in showing entries that don't have a key. 

You mentioned you did some clean-up. Are there any other things, apart from case insensitivity, that come to mind which should be considered by the parser?

**Comment by renerocksai** [comment]
I have just pushed the case-insensitive .bib parsing. Thx again for bringing this up!

**Comment by admin-teametry** [comment]
Hi,

I have similar issues with the BibTeX export from Bookends:

> @Book{Kirsch2014,
> author = {}, 
> title = {Das Mentalisierungskonzept in der Sozialen ArbeitHolger Kirsch}, 
> volume = {}, 
> pages = {177}, 
> editor = {Kirsch, Holger}, 
> publisher = {Vandenhoeck \& Ruprecht}, 
> address = {}, 
> year = {2014}, 
> langid = {}, 
> abstract = {}, 
> keywords = {Mentalisation; Mentalisierung; Master; 5Sem}}

If I use this nothings showing up with "[@" or "[#"

Then I imported all Bookend entries into Zotero and exported again to BibTeX via Zotero:

> @book{kirsch_mentalisierungskonzept_2014,
	title = {Das {Mentalisierungskonzept} in der {Sozialen} {ArbeitHolger} {Kirsch}},
	publisher = {Vandenhoeck \& Ruprecht},
	editor = {Kirsch, Holger},
	year = {2014},
	keywords = {5Sem, Master, Mentalisierung, Mentalisation}

This works. 
Obviously there are somer differences. Is there any possibility using the Bookends export? 
BTW: The Bookends export works fine with pandoc and pandoc-citeproc.

Thanks for this really very helpful plugin. I appreciate it a lot
Andreas
