### ISSUE TITLE
Can’t create notes with shift-enter

### ISSUE THREAD

**Issue by blnk** [renerocksai/sublime_zk#38]
Hi,

since updating the package, I can’t create new notes using shift-enter anymore. Creating new notes by linking to non-existent notes still works.

This is the console output:

```
File "/Users/graphisch/Library/Application Support/Sublime Text 3/Packages/sublime_zk/sublime_zk.py", line 1361, in on_done
    create_note(the_file, new_title, self.origin, self.o_title)
UnboundLocalError: local variable 'new_title' referenced before assignment
```

**Comment by renerocksai** [comment]
You're right. If links_in_titles is false, that's an issue...

**Comment by renerocksai** [comment]
Sorry for that. I've just committed a fix. Wait a bit, update package and it should work.

**Comment by blnk** [comment]
Works perfectly now! Thanks for your quick response!
