### ISSUE TITLE
Feature Request - Place tag in note and then expand to include all notes containing the tag 

### ISSUE THREAD

**Issue by achamess** [renerocksai/sublime_zk#41]
So to make overview notes, it'd be nice to place a tag in a note, and then have that tag expand to place all the notes that include that tag.

For example.

Say I'm writing a note and I place the tag:

#notetaking

It'd be nice to then expand that tag to include all the notes that have it. Like this

- [20180113] Some thoughts on notetaking
- [20180112] More thoughts on notetaking

**Comment by renerocksai** [comment]
You know, when you press `ctrl+enter` on a tag (cursor inside the tag) you get exactly that (without the bullets, though) in the search results so you can copy and paste it...?
What is your perceived benefit of the feature you are requesting? Maybe I'm misunderstanding you?

**Comment by achamess** [comment]
Just one less step. I guess I’m being lazy.

**Comment by renerocksai** [comment]
Oh, OK. I'll give it a thought. We'd probably need a new keyboard shortcut for that as well. Oh hang on, ctrl+. like with the note ids might work...

**Comment by renerocksai** [comment]
Update and check if it's OK 😄 
`ctrl+.` on a tag should expand into the bulleted list of notes with links

**Comment by renerocksai** [comment]
for the README

![expand-tag](https://user-images.githubusercontent.com/30892199/36258162-f198e972-1259-11e8-8b9c-0d6f4519c1e1.gif)

**Comment by renerocksai** [comment]
Also works with citekeys 😄 

![expand-citekey](https://user-images.githubusercontent.com/30892199/36260348-6e56236a-1261-11e8-8046-fb7a9e246b9a.gif)

**Comment by renerocksai** [comment]
And of course, we should also be able to search for all notes that are citing the same source:

![follow-citekey](https://user-images.githubusercontent.com/30892199/36261085-86e70708-1263-11e8-8b0f-fa2c95498b88.gif)

**Comment by achamess** [comment]
Wow Rene.  This is awesome. Thanks so much! I hope that this feature brings value to others who use this. This is a nice and fast way to update the tagged items too. Thanks for being so responsive and accommodating with your ZK package.

Sent from my iPhone

On Feb 15, 2018, at 9:19 AM, Rene Schallner <notifications@github.com<mailto:notifications@github.com>> wrote:


And of course, we should also be able to search for all notes that are citing the same source:

[follow-citekey]<https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_30892199_36261085-2D86e70708-2D1263-2D11e8-2D8b0f-2Dfa2c95498b88.gif&d=DwMFaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=j_eoU9TVYa9LTnnoTWWpgQ&m=YBrBv9la80i0rgOWr61N9_XvMOlWRxuhHsCPAmHiZfY&s=LPynQGPWGGpOBie_TVNaFD2grB7htEXspJwRfdgoVus&e=>
