### ISSUE TITLE
Pandoc & PATH environment variable

### ISSUE THREAD

**Issue by doctornerdis** [renerocksai/sublime_zk#42]
This package is amazing! Thank you so much for making it. It's totally changed the way I work in my Zettelkasten --- and it's really speeded up the process, too.

I have one question from the user guide. For automatic bibliographies you say:

> Note: This will only work if you have pandoc and its companion pandoc-citeproc installed in a location that is referenced by your PATH environment variable!

How can I check if this is the case? And, if it's not, how can I make sure my Zettelkasten, pandoc, and pandoc-citeproc are all in the same place?

**Comment by renerocksai** [comment]
My commit (adding the link to the pandoc install instructions to the readme) closed this issue. Feel free to re-open it if you have problems with it.

**Comment by doctornerdis** [comment]
Thanks!

Just to be clear, I'm using a Mac, and I do have pandoc installed in `/usr/local/bin/`. But when I select and cite key and select `ZK: Auto-Bib`, nothing happens. 

Is there something I'm missing? Do I need to make sure the SublimeText project is saved in a certain spot?

**Comment by renerocksai** [comment]
Oh I see. 
Sooo...first: No, the location of the project does not matter. Your setup seems to be OK!
Also, you don't need to select citekeys. AutoBib creates a bibliography of all cited sources automatically.

So we have two options here:
Either `/usr/local/bin` is not in your path. This may be the case when you've just installed pandoc via homebrew and your macOS environment is not yet aware that homebrew added /usr/local/bin to your path. If that should be the case it might help logging off and logging back in again. `homebrew doctor` might also help...

Option 2: You don't have a `.bib` file in your project and you also don't have a `.bib` file configured in case there is none in your project. But that would mean that you wouldn't be able to insert a citekey via the plugin. Hmmm.

Oh, Option 3: Maybe pandoc doesn't like `.bib` files with blanks in the filename?
