### ISSUE TITLE
Pandoc integration

### ISSUE THREAD

**Issue by doctornerdis** [renerocksai/sublime_zk#43]
#42 

Thanks for your explanation! Sorry to open another issue.

Just to be clear, I'm using a Mac, and I do have pandoc installed in `/usr/local/bin/`. But when I select and cite key and select `ZK: Auto-Bib`, nothing happens.

Is there something I'm missing? Do I need to make sure the SublimeText project is saved in a certain spot?

**Comment by renerocksai** [comment]
I repeat...
Oh I see.
Sooo...first: No, the location of the project does not matter. Your setup seems to be OK!
Also, you don't need to select citekeys. AutoBib creates a bibliography of all cited sources automatically.

So we have two options here:
Either /usr/local/bin is not in your path. This may be the case when you've just installed pandoc via homebrew and your macOS environment is not yet aware that homebrew added /usr/local/bin to your path. If that should be the case it might help logging off and logging back in again. homebrew doctor might also help...

Option 2: You don't have a .bib file in your project and you also don't have a .bib file configured in case there is none in your project. But that would mean that you wouldn't be able to insert a citekey via the plugin. Hmmm.

Oh, Option 3: Maybe pandoc doesn't like .bib files with blanks in the filename?

**Comment by doctornerdis** [comment]
OK, I think we're getting to the issue:

Option 1. I installed pandoc 2.1.1 as a `.pkg` file weeks ago.

Option 2. I have the full path to my bib file in the user settings, something along the line of `/Users/myname/Dropbox/bib_file/library.bib`

Option 3. There are no blanks in the filename. And I've been using this version of Pandoc without a problem in other applications, like Marked 2.

Is there an *Option 4*? Thanks so much for your help.

**Comment by renerocksai** [comment]
Sorry for spamming but there might be something else going on here.

In fact, that would be option 4:

Can you bring up the Sublime Console via `ctrl+\`` (ctrl backtick) or via the menu "view"/"show console" and try to run `ZK: AutoBib` again. It might output a lengthy exception stack trace.

It should also show 'using /Users/myname/Dropbox/bib_file/library.bib'  before that.

**Comment by doctornerdis** [comment]
Here's the output:

```
no command for selector: noop:
Using global /Users/nicholascifuentes-goodbody/Dropbox/bib_file/library.bib
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "/Users/nicholascifuentes-goodbody/Library/Application Support/Sublime Text 3/Packages/sublime_zk/sublime_zk.py", line 1634, in run
    ck2bib = Autobib.create_bibliography(text, bibfile, pandoc='pandoc')
  File "/Users/nicholascifuentes-goodbody/Library/Application Support/Sublime Text 3/Packages/sublime_zk/sublime_zk.py", line 462, in create_bibliography
    citekeys = Autobib.find_citations(text, citekeys)
  File "/Users/nicholascifuentes-goodbody/Library/Application Support/Sublime Text 3/Packages/sublime_zk/sublime_zk.py", line 450, in find_citations
    founds = re.findall('|'.join(list(citekeys)), text)
  File "./python3.3/re.py", line 201, in findall
  File "./python3.3/re.py", line 283, in _compile
  File "./python3.3/sre_compile.py", line 491, in compile
  File "./python3.3/sre_parse.py", line 747, in parse
  File "./python3.3/sre_parse.py", line 359, in _parse_sub
  File "./python3.3/sre_parse.py", line 570, in _parse
sre_constants.error: multiple repeat
```

**Comment by renerocksai** [comment]
Thanks a lot, now we're getting close!!! I will have to digest that for a few minutes but either I made a silly mistake (happens from time to time) or your .bib file contains something the plugin can't digest yet (which could also qualify as silly mistake from me). 

Seeing the final error, it appears to me that you have duplicate citekeys in your .bib file but that's just a wild guess. Let me check ....

**Comment by doctornerdis** [comment]
That might be possible. I'll take a look in my .bib file.

**Comment by renerocksai** [comment]
Is it possible for you to send me a list of all citekeys? 

I now think that one or more of your citekeys has funny characters in it that interferes with the regular expression I am using. To be able to fix it more quickly your citekeys would really help.

Alternatively, can you add the following line 
```
        print('citekeys:', citekeys)
```

so it looks like:
```
        with open(bibfile, mode='r', encoding='utf-8') as f:
            for line in f:
                match = Autobib.citekey_matcher.findall(line)
                if not match:
                    continue
                citekeys.add(match[0])
        print('citekeys:', citekeys)
        return citekeys
```
in sublime_zk.py ?

And send me the output of the console again?

If you don't want to do that,  I have attached `sublime_zk.py.txt` which I needed to rename. So you can rename it back to `sublime_zk.py` and replace your current one.

Meanwhile I will think about how to deal with cite-keys that contain funny characters like `*+},|` etc.

[sublime_zk.py.txt](https://github.com/renerocksai/sublime_zk/files/1729212/sublime_zk.py.txt)

**Comment by doctornerdis** [comment]
Weird. I ran the modified version of `sublime_zk.py` and this is the output:

```
reloading plugin sublime_zk.sublime_zk
Sublime_ZK: Using ag!
Using global /Users/nicholascifuentes-goodbody/Dropbox/bib_file/library.bib
citekeys: set()
```

If it helps, I'm using a bib file that I generated using the latest version of Better BibText.

**Comment by doctornerdis** [comment]
Hold on. Trying something.

**Comment by renerocksai** [comment]
OK, I found a method that can escape dangerous characters in citekeys. However, testing it with `*` and `|` worked, but when feeding them to pandoc to create the bibliographies, pandoc itself got confused.

Now, in your case, as you're using the same setup as I do (I also generate with Better BibTex, not sure if it's the latest version), something else is probably the case. 

As the plugin doesn't seem to recognize a single one of your sources, can you just verbatim copy one or a few harmless (meaning you are happy to share) ones here? I wonder what is going on in your .bib file.

**Comment by doctornerdis** [comment]
I removed some duplicates cite keys from my bib file using JabRef, then re-ran `sublime_zk.py`.

So here is a list of my cite keys: [citekeys.txt](https://github.com/renerocksai/sublime_zk/files/1729289/citekeys.txt)

And here's the output from the console:

```
Using global /Users/nicholascifuentes-goodbody/Dropbox/bib_file/library.bib
citekeys: {ALL THOSE CITEKEYS}
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "/Users/nicholascifuentes-goodbody/Library/Application Support/Sublime Text 3/Packages/sublime_zk/sublime_zk.py", line 1635, in run
    ck2bib = Autobib.create_bibliography(text, bibfile, pandoc='pandoc')
  File "/Users/nicholascifuentes-goodbody/Library/Application Support/Sublime Text 3/Packages/sublime_zk/sublime_zk.py", line 463, in create_bibliography
    citekeys = Autobib.find_citations(text, citekeys)
  File "/Users/nicholascifuentes-goodbody/Library/Application Support/Sublime Text 3/Packages/sublime_zk/sublime_zk.py", line 451, in find_citations
    founds = re.findall('|'.join(list(citekeys)), text)
  File "./python3.3/re.py", line 201, in findall
  File "./python3.3/re.py", line 283, in _compile
  File "./python3.3/sre_compile.py", line 491, in compile
  File "./python3.3/sre_parse.py", line 747, in parse
  File "./python3.3/sre_parse.py", line 359, in _parse_sub
  File "./python3.3/sre_parse.py", line 570, in _parse
sre_constants.error: multiple repeat
```

**Comment by doctornerdis** [comment]
And here are a few entries:

```
@book{dean_self_1992,
  location = {{Ithaca, NY}},
  title = {The Self and Its Pleasures: {{Bataille}}, {{Lacan}}, and the History of the Decentered Subject},
  isbn = {978-0-8014-2660-5 978-0-8014-9954-8},
  shorttitle = {The Self and Its Pleasures},
  pagetotal = {270},
  publisher = {{Cornell University Press}},
  date = {1992},
  author = {Dean, Carolyn J.},
  file = {/Users/nicholascifuentes-goodbody/Zotero/storage/2R27RAAT/dean - 1992 - the self and its pleasures.pdf}
}

@book{brantlinger_bread_1983,
  location = {{Ithaca}},
  title = {Bread \& Circuses: Theories of Mass Culture as Social Decay},
  isbn = {978-0-8014-1598-2},
  shorttitle = {Bread \& Circuses},
  pagetotal = {307},
  publisher = {{Cornell University Press}},
  date = {1983},
  author = {Brantlinger, Patrick},
  file = {/Users/nicholascifuentes-goodbody/Zotero/storage/HEB23RAZ/brantlinger - 1983 - bread & circuses.pdf}
}

@book{keller_higher_2008,
  location = {{Baltimore, MD}},
  title = {Higher Education and the New Society},
  isbn = {978-0-8018-9031-4},
  pagetotal = {188},
  publisher = {{Johns Hopkins University Press}},
  date = {2008},
  author = {Keller, George},
  file = {/Users/nicholascifuentes-goodbody/Zotero/storage/R93MQQ5P/keller - 2008 - higher education and the new society.pdf},
  note = {OCLC: ocn212375923}
}

@book{mottahedeh_iranelection_2015,
  location = {{Stanford, CA}},
  title = {\#iranelection: Hashtag Solidarity and the Transformation of Online Life},
  isbn = {978-0-8047-9587-6},
  shorttitle = {\#iranelection},
  pagetotal = {138},
  publisher = {{Stanford Briefs}},
  date = {2015},
  author = {Mottahedeh, Henry},
  file = {/Users/nicholascifuentes-goodbody/Zotero/storage/5IU72J33/Mottahedeh - 2015 - #iranelection hashtag solidarity and the transfor.pdf}
}
```

**Comment by renerocksai** [comment]
Thanks for sharing this.

Now, to reproduce, may I ask you to share the citekey of the cited source that you want to see in the autobib?

**Comment by doctornerdis** [comment]
Those would be `@cifuentes-goodbody_guadalupe_2015` and `@cifuentes-goodbody_man_2016`.

**Comment by renerocksai** [comment]
Thanks a lot! Now I should be able to check it out. OMG.
It's the DASHES! 
Wow! I was completely unaware of that! Thanks for sharing this!

I put in the fix to escape citekeys and in my test it works.

If you update the plugin it should work now.

If it doesn't, then ping back pls.

That was a tricky one 😄 Thanks for your support!

**Comment by doctornerdis** [comment]
It's working like a charm! Thank you fo your help. (And I'll be sure to take the dashes out of my last name 😜)

Seriously, though, this is a phenomenal piece of work. I learned about this package on Zettelkasten.de, and I'm so glad I did. If you're interested, I run a Slack group for people interested in plain text and Zettelkasten for academic writing. You should join! http://tinyurl.com/y7p9ohg5

**Comment by renerocksai** [comment]
Now you can add as many dashes to all your names as you like 😁 

Thanks! I am really glad you like it and that I'm not the only one who finds it useful 😄 

Wow, cool! Of course I am going to join! It's so rare to find Zettelkasten related resources, I'm really happy for the invitation! Awesome!

**Comment by oolonek** [comment]
Hi guys, 

@renerocksai Thanks a lot for zk ....starting to dive in and this looks really amazing !
@ncgoodbody Is your slack still up ? would be interested to join ...

To both of you.
When I run auto bib I do have a reference list created however it is stated that (no bib is generated)   



```

Lets cite [@Allard2018d] and [@Mickley2019a]



[^footnote]: igjgzug

<!-- references (auto)

[@Allard2018d]: (no bib generated)

[@Mickley2019a]: (no bib generated)


-->

```


Nothing special in the output of the console ...
Any clue ?
