### ISSUE TITLE
Feature Request - Export selected ZK notes as linked HTML

### ISSUE THREAD

**Issue by achamess** [renerocksai/sublime_zk#44]
This is an entirely superfluous and non-essential ask, but I wanted to get it down before I forgot. Please don't feel obliged to touch this at this moment. 

Sometimes it would be nice to export some notes to colleagues. The problem is, they cannot see the zettels that are attached to a given document.

Would it be possible to do an export of a note and its linked notes (and images) as connected HTML files?

**Comment by achamess** [comment]
Long term too, this might be a nice way to share certain parts of a ZK. I've thought about making a script somehow to convert parts of my ZK into a form suitable for something like Jekyll or Hugo.

**Comment by renerocksai** [comment]
I have just released a decent version of [semantic_zk - The Semantic Text View for your Zettelkasten](https://github.com/renerocksai/semantic_zk). It is still early, but is coming together quite nicely. Check out the self-export of its own documentation "Zettelkasten" [here](https://renerocksai.github.io/semantic_zk/).

**Comment by renerocksai** [comment]
btw, as you can see in the issue list of semantic_zk, filtering parts of a ZK is up next 😄

**Comment by achamess** [comment]
This is amazing. Wow! Good work. Thanks so much.

Sent from my iPhone

On Feb 25, 2018, at 6:53 PM, Rene Schallner <notifications@github.com<mailto:notifications@github.com>> wrote:


btw, as you can see in the issue list of semantic_zk, filtering parts of a ZK is up next 😄
