### ISSUE TITLE
Feature Request - New Note from Selection w/ 1st line as Title and subsequent lines as Body

### ISSUE THREAD

**Issue by heychad** [renerocksai/sublime_zk#45]
Rene,
I'm on a roll generating over 20 notes a day with Sublime Text 3 and your plugin!

I've thought of an extension of the already-useful feature to select text and hit `[shift]+[enter]` to create a new note with the selection as the title. I am often writing too much in a single note and wish to move a section into a new note. It would be **amazing** if when selecting more than one line of text and hitting `[shift]+[enter]` that a new note is created with the first line as the pre-populated note title and the subsequent lines copied into the body of the new note. And the selection in the original is replaced by a link to the new note (it already does this).

I'm happy to elaborate on the workflow if you have questions. I think this would make many of us faster in the creation of new notes and new connections between notes. Thanks for taking a look!

Best,
Chad

**Comment by renerocksai** [comment]
Hey Chad 😉,

Wow, 20 notes a day, that's amazing progress!!! I am impressed!

I think I get your idea and it never ceases to amaze me what cool features you and other users come up with. Let me have a look, it doesn't sound unreasonable what you're asking here and I think it can be done.

Cheers,
Rene

**Comment by renerocksai** [comment]
Done 😄

**Comment by renerocksai** [comment]
Now I just need to update the README 😄 
Thanks for this suggestion! Playing with it I can already see how useful it is 👍
