### ISSUE TITLE
consider removing syntax dependency

### ISSUE THREAD

**Issue by toolboxen** [renerocksai/sublime_zk#5]
I noticed you're using `sublime_zk.sublime-syntax` to provide underlining for the zettel links.

However this might cause problems with zettelkasten users who use other markdown syntaxes.

perhaps there is a syntax agnostic approach to providing these highlights which would allow people to use multiple types of Markdown-related syntaxes along with this plugin. For example if users are writing their zettelkasten with [Academic markdown](https://packagecontrol.io/packages/AcademicMarkdown) they will not currently be able to use your package highlighting.

however if your package applied highlighting using a regex filter then perhaps it could apply to multiple syntaxes?

**Comment by renerocksai** [comment]
Tricky tricky. I thought the syntax file is more clean than providing highlighting in code. It works well with MarkdownExtended package. But I don't want to shut out the academic crowd. This one requires a little more thought... My highlighter class would definitely be able to provide highlighting for the footnotes without using a syntax file. But it would need to be done right. We don't want to mix links and footnotes :)

**Comment by toolboxen** [comment]
One option is to split out the footnote feature into another package and just provide linking/note-creation functionality with this plugin. Several of the markdown packages available on packagecontrol.io already provide footnote coloring.

As it stands now this plugin is providing link highlighting without needing the syntax to be markdown related. It highlights even the example link the python code ;)

**Comment by renerocksai** [comment]
Yeah, I noticed how MarkdownEditing, for example, does the footnote
coloring - but I can't stand how it centers my text, etc. So I like
MarkdownExtended - which has no support for the footnotes...

I am leaning towards moving the footnote coloring into the code and have a
setting that's false by default. So I can enable it for myself and people
using better Markdown packages don't need to bother with it.

Regarding the link highlighting: yes, I kind of like it that way. I ignore
the syntax of the view. Highlighting only applies to 12-digit numeric IDs
in brackets, so it shouldn't interfere too much in unintended ways.

**Comment by toolboxen** [comment]
> I am leaning towards moving the footnote coloring into the code and have a setting that's false by default. So I can enable it for myself and people using better Markdown packages don't need to bother with it.

that would work! And ignoring the syntax of the view for link highlighting is how I would have implemented the functionality myself. good choice.

**Comment by toolboxen** [comment]
This issue is related so I'm continuing the discussion from https://github.com/renerocksai/sublime_zk/issues/2#issuecomment-341837790

It's up to you. A custom syntax has some benefits. It's the normal way to handle highlighting in Sublime, and is the way that most users will expect a plugin to apply highlights to text.

Right now you're kind of in a middle ground between a custom syntax and not.

- With the footnotes you've got a syntax file and with this method Sublime does the scoping for you based on the definitions you set in the syntax file.

- With the links you're setting the scopes programatically after Sublime has done the first scoping pass, and then you're also applying the styling programatically. (Which you have to do anyway since you're using the `flags` to style the text) -- as I mentioned before this adds an extra scoping pass.

I suggest normalizing to use one method or the other:

1. Either put all the regexes into the syntax file, let Sublime do all the scoping for you, and apply highlighting afterward.

2. Put all the regexes into the plugin, apply the scoping and highlighting programatically, and remove the syntax file dependency in the repo.

Using method 1 is the way most users will expect. It keeps all your scopes related in a single syntax file, and other users can embed it within their own syntaxes, or can duplicate the syntax over to existing Markdown-related syntaxes. Also, it's faster since all the scoping is handled by Sublime.

However, doing it all programatically means that you can provide link & footnote styling regardless of syntax. Your link & footnote highlighting would work across all Markdown-related syntaxes. However it might collide with some of the syntaxes if they are trying to highlight the same scopes you are. Also it might not be apparent to users where the highlighting is actually occuring since most will expect a syntax file to be responsible instead of a plugin.

My gut feeling is that Method 1 is probably going to lead to the most compatibilty with other markdown-related syntaxes, will be easier to use for users familiar with Sublime Text paradigms, and will also lead to less "customer support" for you since you'll be handling everything as closely to "Sublime Text standards" as described in the documentation.

**Comment by renerocksai** [comment]
So far my results, as in the `feature_syntax_highlighting` branch: scoping works but of course it only scopes and I have yet to find a color scheme that does the underlining. gutter icons are gone, too :-|

**Comment by toolboxen** [comment]
> gutter icons are gone, too :-|

hmmmm... that's a bummer. fwiw, if you're using sublimelinter or gitgutter you'll have conflicts: https://stackoverflow.com/questions/34190046/

**Comment by toolboxen** [comment]
> I have yet to find a color scheme that does the underlining

Once the scope is applied you can use the `flags` to apply the highlighting programatically.

**Comment by renerocksai** [comment]
I am not sure I understand. But I'll check the docs. At the moment, I use
`view.add_regions` to set the flags - which also gives them a scope...

Am 04.11.2017 05:34 schrieb "toolboxen" <notifications@github.com>:

I have yet to find a color scheme that does the underlining

Once the scope is applied you can use the flags to apply the highlighting
programatically.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/renerocksai/sublime_zk/issues/5#issuecomment-341871300>,
or mute the thread

**Comment by toolboxen** [comment]
Does something like this work? I'm not as familiar with this as I should be.

```
view.add_regions(
    "zettel_link",
    view.find_by_selector("markup.underline"),
    "markup.underline.link",
    flags = sublime.DRAW_NO_FILL | sublime.DRAW_NO_OUTLINE | sublime.DRAW_SOLID_UNDERLINE
)
```

**Comment by toolboxen** [comment]
Or actually it should be a unique scope as defined in syntax file?

```
view.add_regions(
    "zettel_link",
    view.find_by_selector("markup.zettel"),
    "markup.zettel.link",
    flags = sublime.DRAW_NO_FILL | sublime.DRAW_NO_OUTLINE | sublime.DRAW_SOLID_UNDERLINE
)
```

and in syntax file

```
        - match: '(\[)([0-9]{12})(\])'
          captures:
            '1': punctuation.definition.footnote.begin.markdown
            '2': markup.zettel.link
            '3': punctuation.definition.footnote.begin.markdown
```

**Comment by renerocksai** [comment]
i have half of it in the new branch now.
it's just that I am still searching for the regions "manually" at the moment but I'm trying to switch that.

how does one easily extend the color scheme to support such links?
for the moment I put the additional scope 'keyword' just in the syntax file. as a consequence the gutter icon and underline are a different (default) color. that's a compromise :)

**Comment by renerocksai** [comment]
This is a sublimetext bug. It's not well thought ought, the gutter icon
thing,

But: at least we can disable the icons in the settings file. So if one uses
gitgutter for instance, they can disable bookmarks in our plugin.

**Comment by renerocksai** [comment]
I now select the regions by the scope selector. Still have to keep track of them at every update so the change is minimal. Performance-wise it probably is an improvement.

if only there would be a way to easily add a color for markup.zettel into one's color scheme...

**Comment by renerocksai** [comment]
I updated the README with minimal instructions about the color scheme, tweaked my color scheme, and made it part of the repo. That's a compromise I can live with.

**Comment by renerocksai** [comment]
:-)

**Comment by toolboxen** [comment]
I like it! The link coloring against the monokai theme looks good. Your extensive documentation in the readme will help users as well. Good stuff! 👏
