### ISSUE TITLE
automatic installation is not working

### ISSUE THREAD

**Issue by pkritiya** [renerocksai/sublime_zk#50]
Added repository, https://github.com/renerocksai/sublime_zk, but the package is not found from package control - can't do automatic installation. Any work around to this problem?

**Comment by renerocksai** [comment]
Hi, I just checked and get the same behaviour. This seems to be a package control issue. I will try to research what's causing this. I'll also dig into package control. Last time I checked its documentation it appeared to be quite an involved process to get something into the main channel.

One other user reported in the past that it took a few minutes until they were able to get the latest version after I had pushed it to GitHub. So maybe it just takes time...

**Comment by renerocksai** [comment]
BTW the workaround you probably have discovered already is to just download / clone from GitHub into your packages directory

**Comment by renerocksai** [comment]
Update: Package control works with the added repository.
The reason I couldn't install via package control is because it figured out that I already had that package from the same github repository installed (manually) already.

When I "package control: list packages", it shows "sublime_zk". 

I suspect, by reading installation/re-installation in #51, that your case is similar.

Can you confirm?

**Comment by pkritiya** [comment]
Well, I have tried with two machines. One of them is a new Mac, which I haven't installed any version of sublime text. Package control automatic install didn't work with this new machine as well. I think it could be a package control issue as you said. Thanks for your quick reply!

**Comment by renerocksai** [comment]
Hmmm, that's very odd. BTW I have made a few changes to make it package control compatible and have sent them a pull request. it is awaiting review, don't know how long it will take but soon it should work again.

I noticed some weird package control glitch a few days ago when I wanted to install the pandoc package on a new machine. it was gone, not installable. a day or two later, it was back. So maybe what you are getting is the odd package control hickup.

**Comment by pkritiya** [comment]
Definitely the problem is caused by Korean tags - I created a new project that has no Korean tags and the search works perfectly. 

I just copied some Korean tags for you to work with

#행복  #안녕하세요  #서브라임  #사회 #사회란무엇인가

Thanks for your quick reply!!

**Comment by comunity-tools** [comment]
Same problem here (running Gentoo) I added the repo but cannot see the package

**Comment by jonathan-s** [comment]
And same here, added the repo but can't see the package.

**Comment by renerocksai** [comment]
This is unfortunate, I guess something in package control is broken. 9 days ago I made sublime_zk package-control compatible and filed for inclusion via pull request https://github.com/wbond/package_control_channel/pull/6991 . So far, it hasn't been included and is one of the many pull requests idling around there.

If package control doesn't work (with the added GitHub repository), for now I can only recommend the [manual installation](https://github.com/renerocksai/sublime_zk#manual-installation).

Sorry about that. I hope package control will fix this issue soon.

**Comment by comunity-tools** [comment]
Thank you very much, I did the manual installation and it works.

The package is awesome!


2018-03-18 22:29 GMT+01:00 Rene Schallner <notifications@github.com>:

**Comment by renerocksai** [comment]
Here is the fix, see:
 
* https://github.com/wbond/package_control/issues/736#issuecomment-286146605
* https://forum.sublimetext.com/t/st3-3126-package-control-ssl-cert-invalid-errors-reinstall-didnt-help/23539
* https://forum.zettelkasten.de/discussion/comment/1160/#Comment_1160

Use the menu to open the PackageControl settings:

* Preferences > Package Settings > Package Control > Settings - User

Add the following lines (e.g. after `"bootstrapped": true,":

```json
	"downloader_precedence":
	{
		"linux":
		[
			"urllib",
			"curl",
			"wget"
		],
		"osx":
		[
			"curl",
			"urllib"
		],
		"windows":
		[
			"wininet"
		]
	},
```

This forces package control to use `curl` on OS X which can handle GitHub certificates (I think) 😄

**Comment by comunity-tools** [comment]
Thank you very much!! I will try it

2018-03-31 23:25 GMT+02:00 Rene Schallner <notifications@github.com>:

**Comment by LastQuinsy** [comment]
@renerocksai thank you so much*) Killed for several days to find this post and fix the problem =. =
