### ISSUE TITLE
Centering of text

### ISSUE THREAD

**Issue by jonathan-s** [renerocksai/sublime_zk#53]
One feature that I particularly like in this package https://github.com/SublimeText-Markdown/MarkdownEditing is that when editing markdown all text is centered. Would be really nice to see this here too.

**Comment by renerocksai** [comment]
This is a very specific personal preference. While I am sure it can be done (MarkdownEditing is proof), I would certainly not make it the default. I guess, it would drive me nuts. But it's a reasonable request and I will try to make a centered mode.

Can you be more specific? Any pointers would help. I looked at a few screenshots in the MDE repository and none of them had centered text...

**Comment by renerocksai** [comment]
I just checked: Centering is actually a SublimeText feature: just add this to your settings, e.g. the sublime_zk User preferences:

```
    "draw_centered": true,
```

... and you get centered text.

**Comment by jonathan-s** [comment]
Though using that option, it doesn't at all get the same result as in markdown editing. There the standard case is that you get some margin. 

Well, I'll see if I can figure out how they do it, and perhaps there will be a PR where you can use that as a setting.
