### ISSUE TITLE
New note template - only title

### ISSUE THREAD

**Issue by jonathan-s** [renerocksai/sublime_zk#55]
It looks like `{title}` gives you the id + the title. Whereas it would be desirable to only get the title. 

Sorry for all the new issues 😅

**Comment by jonathan-s** [comment]
It was a setting mistake. But perhaps it would be prudent to make ``id_in_title`` false by default? And then have the default template to be the following, as it is now. 

At least it feels slightly unintuitive to me having that set to true by default, if you start to change your own template. 

```
# 201803182208 test a new note
tags =

```

**Comment by renerocksai** [comment]
Yeah, good catch. `id_in_title` is partly a relic from pre-note-template times. I guess, setting it to `false` by default is a sensible thing to do.

BTW: Keep the issues coming. They're a way to improve the package for all of us 😄

**Comment by renerocksai** [comment]
I just pushed the `id_in_title: false`
