### ISSUE TITLE
Insert wiki link with title

### ISSUE THREAD

**Issue by jonathan-s** [renerocksai/sublime_zk#56]
Was thinking it could be nice to insert a wiki link with a title. In the following format `[[20181321231]](some title here)`. Using parenthesis would make it reasonably easy to parse to and transform that into something else if, let's say the markdown went through a static site generator and you wanted that to be a `<a href>` tag with a title. 

Also see #58, which is related.

**Comment by renerocksai** [comment]
So, instead of `[[201803222153]](some title)`, would you consider `[[201803222153 some title]]`, too? Should be very simple to parse. I do it all the time 😉.

**Comment by jonathan-s** [comment]
Ah, you are correct it shouldn't be too difficult to parse that with regex and transform to something desirable.
