### ISSUE TITLE
Autocomplete for tags

### ISSUE THREAD

**Issue by jonathan-s** [renerocksai/sublime_zk#59]
It's somewhat difficult to remember tags you've used before, hence the option of finding all the tags in your archive. An improvement would be that once you start with `#` an autocomplete dropdown would appear and as you type it would narrow down to the given tags.

**Comment by renerocksai** [comment]
This would probably get in the way of entering `[local references](#local-references)` and `# heading1`, etc.

Why not use the [tag selector](https://github.com/renerocksai/sublime_zk#experimental-tag-selector) `#?` ? It's one more key-press and you get fuzzy search...

**Comment by jonathan-s** [comment]
Had missed that!
