### ISSUE TITLE
Find notes in subdirectories

### ISSUE THREAD

**Issue by jonathan-s** [renerocksai/sublime_zk#60]
As stated in the post found at the [zettelkasten forum][1]. Currently the plugin only finds notes in the first directory, not in subdirectories. 

[1]: https://forum.zettelkasten.de/discussion/comment/709/#Comment_709

**Comment by renerocksai** [comment]
That's already implemented. If it doesn't work in your case, can you provide some details. Anything suspicious about your subdirectories?

**Comment by jonathan-s** [comment]
I was just too quick to add the issue! Continued to read the thread and saw that it had been implemented.
