### ISSUE TITLE
Tag search not working

### ISSUE THREAD

**Issue by chris-zettelkasten** [renerocksai/sublime_zk#62]
Hi there,
I just installed sublime_zk and it works really fine, I like it. Unfortunately the search for tags and their related files seems not to work. When using alt + enter nothing happens.
I use Linux Mint 18.3, ag is installed.
Maybe I can get some help?
Best regards (and thx a lot for your awesome package, it's really great!) -
Chris

P.S.: I did a workaround and added a line in keymap to zk_multi_tag_search, which works for a single tag also. But that means hotkey plus typing your tag... :(

**Comment by renerocksai** [comment]
For tags it's ctrl+enter, which may be a bit confusing. Alt+enter is only for finding "friend notes"...

**Comment by renerocksai** [comment]
I can see why you hit alt+enter. 🙂 
The idea behind the key bindings  was: ctrl + enter performs default action on note link or tag, while alt+enter was needed for note links to add the find friends functionality . Also, that functionality was introduced after Ctrl+enter was implemented...

**Comment by chris-zettelkasten** [comment]
Thx for your fast reply. Unfortunately ctrl+enter doesn't work for me either...

**Comment by renerocksai** [comment]
It's fixed. If you update now, ctrl+enter will work for your tags

**Comment by chris-zettelkasten** [comment]
Man - that's fast as hell :)
Thx a lot!
