### ISSUE TITLE
Sort order

### ISSUE THREAD

**Issue by chris-zettelkasten** [renerocksai/sublime_zk#64]
Since I switched to Linux and cannot use The Archive anylonger, I'm really happy with sublime_zk (I like it much more than ZIM, even though ZIM is a great tool without a doubt).

There is only one thing which is not that good as I see it - when searching for friends or notes related to a tag, the results will be sorted by the UID and not the title. When having lots of results it is a bit uncomfortable to look up for a certain note quickly.

So, not an issue but serious request:
I don't know anything about coding and do not know, if this could be done, but: I would like to see the search results sorted alphabetically by title. Would improve smooth working with sublime_zk...
Just as an idea.

Cheers -

Chris

**Comment by renerocksai** [comment]
new setting (set to title):

```
    // Sort note lists (search results) by
    // - title
    // - ID       <-- default
    "sort_notelists_by": "id"
```

**Comment by chris-zettelkasten** [comment]
Thx Rene, great job!
With most of my tags it seems to work fine. 
But I found that with some tags it's not working at all - tags I know there definitely are files containing those. Is it cos I changed my tag's prefix from # to @?

**Comment by renerocksai** [comment]
Please provide more details. So, the problem was: sort order. I have changed that. Now it seems, something tag related is not showing up. And you have changed the tag prefix.
You can only have 1 tag prefix. If some of your notes use `#tag` and some use `@tag` you will only find one set of tags.
Also, there could, although I can't see them when I look at the code, be side-effects because `@` is also used for cite-keys. Anyhow, I would need more details, I cannot figure out what your problem is exactly

**Comment by chris-zettelkasten** [comment]
1) I use @ as tag prefix, changed this in the .py file (line 35)  and the settings (line 22).

2) The 'old' version of sublime_zk works wonderful and smooth. No issues. 

3) I then asked if the sort order could be changed according to the title. You changed it.

3) I updated the old .py and the settings with your new files. Changed the prefix in this file as in 1) Also changed "id" to "title" in the settings (at the end of the settings).

4) Now with some tags the search results are sorted alphabetically, that's great. But with other tags there is only this output: "Notes referencing @xyz:" - but the referencing notes (which definitely exists) are not shown.

5) I re-changed all tag prefixes of my Zettelkasten back to '#' to see, if the problem may come from the prefix. Also in your files (see 1)). But I get the same problem.

6) Meanwhile I changed back to the 'old' .py and settings and with ALL tags (after ctrl+enter) I get the correct search results (they are sorted by ID, but hey, in the end I can live with this).

Tut mir leid, ich gebe nur wieder, was mir aufgefallen ist. Wenn ich mehr wüsste, teilte ich es Dir selbstverständlich mit. Hoffe, dass nun das Problem deutlicher geworden ist.
Besten Gruß und nochmal herzlichen Dank für Deine tolle Arbeit -

Chris

**Comment by renerocksai** [comment]
No need to be sorry. Let's throw some emojis in here 😄😅😎      
I want to improve things, but sometimes I just can't get my head around about what's going wrong.

So, to sum it up, if I understand you correctly, you experience: 

* sorting by title makes some search results disappear when searching for notes referencing specific tags.
* the tag prefix (e.g. '#' or '@') makes no difference in this regard
* setting the sorting to `id` does not show this behaviour, right?

By the way: You only need to change the tag prefix in the settings, not also in the python file. The '#' is just in there out of the habit to leave no config variable uninitialized.

If you can test, can you fire up the sublime console (view > show console) after setting sorting to `title` again and try with a tag that you know doesn't work --- and see if that produces a lengthy exception output.

I have a vague idea what could be causing the issue; that is if you have notes that don't match the `2018xxxxxxxx... title` scheme, like `test.md`. But I need to check... If that were the case, it can be fixed easily. I am just trying to re-produce your bug.

**Comment by renerocksai** [comment]
So.... I cannot re-produce. Can you send me some of your files where it doesn't work? You can strip out as much of the tags as you like, maybe just leave the tags in there. Like, a file that shows up in the search and a file that doesn't?

**Comment by chris-zettelkasten** [comment]
> I have a vague idea what could be causing the issue; that is if you have notes that don't match the 2018xxxxxxxx... title scheme, like test.md. But I need to check... If that were the case, it can be fixed easily. I am just trying to re-produce your bug.

YEAAAAAAAAAAAAAAAAAAAH! I removed all files without the requested title scheme - and BANG! 
Rene, thx so much. It's working. Man, I'm so happy.

Now I got my perfect ZettelKasten-Tool :) :+1:

**Comment by renerocksai** [comment]
😄 awesome! I just pushed a change that makes at least the tag based search not break again when you have `test.md` like files.
