### ISSUE TITLE
Idea: Create markdown link with url from bibliography

### ISSUE THREAD

**Issue by cnicolai** [renerocksai/sublime_zk#65]
Hi Rene,
first of all thank you for this great plugin! :)

I just had an idea I wanted to share with you. If an entry in the bibliography has an url attached to it, wouldn't it be cool to use that url to create a markdown link?

So for example, if the bibliography file contains the following entry

```
@book{citekey,
	author = {Donald Duck},
	title = {Graphtheory},
	year = {2018},
	publisher = {Dagobert Duck},
	url = {www.graphtheorybook.org}
}
```

the "zk_insert_citation" command could insert `[@citekey](www.graphtheorybook.org)` instead of just `[@citekey]`.

What do you think about that?
Unfortunately I don't know anything about Sublime plugins so I can't provide a PR.

**Comment by renerocksai** [comment]
Well, this is certainly possible to implement but I would not do it, it's totally not pandoc and thus results in pandoc just appending the `(http://.....)` as if it was ordinary text. It doesn't convert it into a clickable link, so I don't see the point.

See https://pandoc.org/MANUAL.html#citations.

Simple markdown converters (such as python's markdown module) treat it as a link which might be what you're after -- but they are forced to use the `@citekey` as link title, which also looks a bit odd.

So all in all, I am not convinced.

**Comment by cnicolai** [comment]
Hi,
what you say totally makes sense, thanks for pointing it out :-)
