### ISSUE TITLE
Display error in "Insert Citation" fuzzy-searchable list; all instances of the string "and" display as "&" 

### ISSUE THREAD

**Issue by argonsnorts** [renerocksai/sublime_zk#68]
Just a minor issue. As the title suggests, in the drop-down fuzzy-searchable list that appears after the "Insert Citation" command "[#", all instances of the string "and" appear as "&", regardless of where the "and" appears, even in the middle of a word.

Appended below are a few screen grabs that hopefully show the behavior, particularly in regard to the names "Ramachandran" and "Strand."

Kudos to you for putting together such an excellent Zettelkasten package. This is the first issue I've come across in the three months I've been using Sublime ZK. Great work, and many thanks to you!

![photo1](https://user-images.githubusercontent.com/35884142/38176019-87303342-35ef-11e8-9974-f2e013b76c89.png)
![photo2](https://user-images.githubusercontent.com/35884142/38176020-87526002-35ef-11e8-9cd2-77222481c111.png)
![photo3](https://user-images.githubusercontent.com/35884142/38176021-87773710-35ef-11e8-971e-ae9b1f929223.png)
![photo4](https://user-images.githubusercontent.com/35884142/38176022-8798042c-35ef-11e8-89e0-6c609b084fae.png)
![photo5](https://user-images.githubusercontent.com/35884142/38176023-87b9e56a-35ef-11e8-88ca-3399945a51fa.png)

**Comment by renerocksai** [comment]
Thanks & thank you for your detailed bug description! 👍 

😄 Yeah, that was a silly mistake. I separated authors with `and` instead of ` and` (with leading space), in order to figure out when to produce _et al._

It's fixed now.

**Comment by argonsnorts** [comment]
Thanks for the quick fix! And thanks again for Sublime ZK. It's becoming like a third hand -- I don't know what I did without it!
