### ISSUE TITLE
prevent packed installation by adding .no-sublime-package

### ISSUE THREAD

**Issue by toolboxen** [renerocksai/sublime_zk#8]
I may have screwed up something as I'm having trouble installing with package control haha! I thought I had it well tested but apparently not. investigating now...

**Comment by renerocksai** [comment]
ok, no worries. create a pull request or just let me know when you know more.

**Comment by toolboxen** [comment]
ahhh, it's an issue with how package control installs the plugin from the repository. by default they are installed as packed files but the script is written expecting an unpacked folder: https://packagecontrol.io/docs/customizing_packages

**Comment by renerocksai** [comment]
OK so you're figuring placing a `.no-sublime-package` file into the
repository should do the trick for now?

**Comment by toolboxen** [comment]
indeed!

**Comment by renerocksai** [comment]
done. check it out and if this is a (temporary) fix then i'll close the issue

**Comment by toolboxen** [comment]
boom! perfect. works great!

And this isn't a temp fix as the plugin is currently written to expect an open folder installed directly under `/Packages/` so even if you submit this to packagecontrol.io it will need a re-write to support the packed version which is essentially a zipped file with the file extension of `.sublime-package`
