### ISSUE TITLE
readme: false is boolean not string

### ISSUE THREAD

**Issue by toolboxen** [renerocksai/sublime_zk#9]
I forgot to update readme in section https://github.com/renerocksai/sublime_zk#ids-in-titles-of-new-notes `"false"` should be `false` now that the settings options are Boolean instead of string

**Comment by renerocksai** [comment]
got you covered, will change readme

**Comment by toolboxen** [comment]
aaaand I didn't notice but there is also several instances of `"true"` where they should be just true

**Comment by renerocksai** [comment]
hang on, let me check and fix this once and for all :)

**Comment by toolboxen** [comment]
sorry about that! 😝

**Comment by renerocksai** [comment]
ok, it's done 😉

**Comment by toolboxen** [comment]
nice! ty.
